//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myDataBaseEntities : DbContext
    {
        public myDataBaseEntities()
            : base("name=myDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blogs> Blogs { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Dados> Dados { get; set; }
        public virtual DbSet<Imagens> Imagens { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
